language: python
services:
  - docker
env:
  - ENV=centos7_nginx PGVER=pg10 JAVAVER=openjdk1.8
  - ENV=ubuntu1804_nginx PGVER=pg10 JAVAVER=openjdk1.8
  - ENV=ubuntu1604_nginx
  - ENV=debian9_nginx
  - ENV=ubuntu1804_nginx
  - ENV=centos7_nginx

before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - PGVER=$PGVER ./docker-build.sh $ENV
    - ./test_services.sh
    - cd ..
    - ./autogenerate.sh
