language: python
services:
  - docker
env:
  - ENV=centos6
  - ENV=ubuntu1404
script:
    - cd linux/test && ./docker-build.sh $ENV && docker run -ti omero_install_test_$ENV
    # Sadly, no test for Windows or OS X here.
