language: python
services:
  - docker
env:
  - ENV=centos7 PGVER=pg10 JAVAVER=openjdk1.8
  - ENV=ubuntu1804 PGVER=pg10 JAVAVER=openjdk1.8
  - ENV=ubuntu1604
  - ENV=debian9
  - ENV=ubuntu1804
  - ENV=centos7
  - ENV=debian10


before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - PGVER=$PGVER ./docker-build.sh $ENV
    - ./test_services.sh
    - cd ..
    - ./autogenerate.sh
