language: python
services:
  - docker
env:
  - ENV=centos7_nginx  WEBSESSION=true
  - ENV=centos7_apache24 WEBSESSION=true
  - ENV=centos6_nginx
  - ENV=centos6_apache22
  - ENV=centos6_py27_nginx WEBSESSION=true
  - ENV=centos6_py27_apache24 WEBSESSION=true
  - ENV=ubuntu1404_nginx WEBSESSION=true
  - ENV=ubuntu1404_apache24 WEBSESSION=true
  - ENV=debian8_nginx WEBSESSION=true
  - ENV=debian8_apache24 WEBSESSION=true
  - ENV=centos6_py27_ius_apache22 WEBSESSION=true
  - ENV=centos6_py27_ius_apache24 WEBSESSION=true
  - ENV=centos6_py27_ius_nginx WEBSESSION=true

before_install:  
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine

script:
    - cd linux/test
    - ./docker-build.sh $ENV
    - if [[ "$ENV" =~ "centos7" ]]; then ./test_services.sh; fi
    # Sadly, no test for Windows or OS X here.
