language: python
services:
  - docker
env:
  - ENV=centos7_nginx PGVER=pg10
  - ENV=ubuntu1604_nginx PGVER=pg10
  - ENV=debian9_nginx PGVER=pg10
  - ENV=centos7_nginx PGVER=pg96
  - ENV=ubuntu1604_nginx PGVER=pg96
  - ENV=debian9_nginx PGVER=pg96
  - ENV=ubuntu1604_nginx JAVAVER=openjdk11

before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - PGVER=$PGVER ./docker-build.sh $ENV
    - if [[ "$ENV" =~ "centos7" ]]; then ./test_services.sh; fi
    - cd ..
    - ./autogenerate.sh
