language: python
services:
  - docker
env:
  - ENV=centos7_nginx
  - ENV=centos6_py27_ius_nginx
  - ENV=ubuntu1604_nginx
  - ENV=debian9_nginx

before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - ./docker-build.sh $ENV
    - if [[ "$ENV" =~ "centos7" ]]; then ./test_services.sh; fi
    - cd ..
    - ./autogenerate.sh
